
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.analizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 17;
  public static final int PUNTOYCOMA = 23;
  public static final int DOSPUNTOS = 29;
  public static final int DECIMAL = 32;
  public static final int CORCHETEDERECHO = 26;
  public static final int PALABRA = 30;
  public static final int EJECUTAR = 21;
  public static final int PARENTESISDERECHO = 22;
  public static final int ETIQUETA = 8;
  public static final int POR = 18;
  public static final int TIPO = 11;
  public static final int PORCENTAJE = 15;
  public static final int LLAVEDERECHA = 28;
  public static final int BARRAS = 3;
  public static final int VALORES = 9;
  public static final int COMA = 24;
  public static final int LLAVEIZQUIERDA = 27;
  public static final int CORCHETEIZQUIERDO = 25;
  public static final int EOF = 0;
  public static final int TOTAL = 12;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int EXTRA = 13;
  public static final int CANTIDAD = 14;
  public static final int PARENTESISIZQUIERDO = 20;
  public static final int error = 1;
  public static final int DIAGONAL = 19;
  public static final int EJEY = 7;
  public static final int EJEX = 6;
  public static final int ENTERO = 31;
  public static final int UNIR = 10;
  public static final int TITULO = 5;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETA",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "CANTIDAD",
  "PORCENTAJE",
  "MAS",
  "MENOS",
  "POR",
  "DIAGONAL",
  "PARENTESISIZQUIERDO",
  "EJECUTAR",
  "PARENTESISDERECHO",
  "PUNTOYCOMA",
  "COMA",
  "CORCHETEIZQUIERDO",
  "CORCHETEDERECHO",
  "LLAVEIZQUIERDA",
  "LLAVEDERECHA",
  "DOSPUNTOS",
  "PALABRA",
  "ENTERO",
  "DECIMAL"
  };
}

